version: '3.8'   
name: cv
services:
  cv:
    build: .
    restart: unless-stopped
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "4949:4949"
      - "80:80"
      - "4000:4000"
    environment:
      ENVIROMENT: pro