# Generated by Django 5.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0001_initial"),
    ]

    operations = [
        migrations.AddField(model_name="visitsession", name="browser", field=models.CharField(blank=True, max_length=40)),
        migrations.AddField(model_name="visitsession", name="color_scheme", field=models.CharField(blank=True, max_length=12)),
        migrations.AddField(model_name="visitsession", name="connection_effective", field=models.CharField(blank=True, max_length=20)),
        migrations.AddField(model_name="visitsession", name="connection_type", field=models.CharField(blank=True, max_length=40)),
        migrations.AddField(model_name="visitsession", name="continent", field=models.CharField(blank=True, max_length=40)),
        migrations.AddField(model_name="visitsession", name="cores", field=models.PositiveSmallIntegerField(blank=True, null=True)),
        migrations.AddField(model_name="visitsession", name="country_code", field=models.CharField(blank=True, max_length=8)),
        migrations.AddField(model_name="visitsession", name="device", field=models.CharField(blank=True, max_length=40)),
        migrations.AddField(model_name="visitsession", name="downlink", field=models.FloatField(blank=True, null=True)),
        migrations.AddField(model_name="visitsession", name="isp", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="visitsession", name="landing_path", field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name="visitsession", name="language", field=models.CharField(blank=True, max_length=40)),
        migrations.AddField(model_name="visitsession", name="memory_gb", field=models.FloatField(blank=True, null=True)),
        migrations.AddField(model_name="visitsession", name="org", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="visitsession", name="os", field=models.CharField(blank=True, max_length=40)),
        migrations.AddField(model_name="visitsession", name="pixel_ratio", field=models.FloatField(blank=True, null=True)),
        migrations.AddField(model_name="visitsession", name="platform", field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name="visitsession", name="postal", field=models.CharField(blank=True, max_length=20)),
        migrations.AddField(model_name="visitsession", name="referrer", field=models.TextField(blank=True)),
        migrations.AddField(model_name="visitsession", name="screen", field=models.CharField(blank=True, max_length=24)),
        migrations.AddField(model_name="visitsession", name="timezone_client", field=models.CharField(blank=True, max_length=64)),
        migrations.AddField(model_name="visitsession", name="timezone_ip", field=models.CharField(blank=True, max_length=64)),
        migrations.AddField(model_name="visitsession", name="touch", field=models.BooleanField(blank=True, null=True)),
        migrations.AddField(model_name="visitsession", name="utm_campaign", field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name="visitsession", name="utm_medium", field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name="visitsession", name="utm_source", field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name="visitsession", name="viewport", field=models.CharField(blank=True, max_length=24)),
    ]
